Repository nert-nlp/legal-cgel, pull requests merged in 2025-02, with the labels that each got.

#118 #104 usc-004: extra `Nom` layer above "section 511(a)"
  datasets/oneoff/pdf/usc-004.id4eaa5dfe-50c2-11ef-9dd1-d8c68483f815_2_0.pdf
  datasets/oneoff/tex/usc-004.id4eaa5dfe-50c2-11ef-9dd1-d8c68483f815_2_0.tex
  datasets/oneoff/usc-004.id4eaa5dfe-50c2-11ef-9dd1-d8c68483f815_2_0.cgel
Labels: tree edit

#117 #104 usc-009: `Nom` layer above "biosurveillance activities"; "biosurveillance" = `Nom`
  datasets/oneoff/pdf/usc-009.iddfbeb130-2a49-11ef-964b-eac34d51b403_2_0.pdf
  datasets/oneoff/tex/usc-009.iddfbeb130-2a49-11ef-964b-eac34d51b403_2_0.tex
  datasets/oneoff/usc-009.iddfbeb130-2a49-11ef-964b-eac34d51b403_2_0.cgel
Labels: tree edit

#112 #107 usc-047: place "amounts found..." :Mod Clause within Nom
  datasets/oneoff/pdf/usc-047.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_0.pdf
  datasets/oneoff/tex/usc-047.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_0.tex
  datasets/oneoff/usc-047.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_0.cgel
Labels: tree edit

#113 #106 usc-012: move coordinated modifier "design... operational"
  datasets/oneoff/pdf/usc-012.id327c7597-f59a-11ee-9f93-9b257bd089f3_2_0.pdf
  datasets/oneoff/tex/usc-012.id327c7597-f59a-11ee-9f93-9b257bd089f3_2_0.tex
  datasets/oneoff/usc-012.id327c7597-f59a-11ee-9f93-9b257bd089f3_2_0.cgel
Labels: tree edit

#115 #104 usc-001: "Recognition" and "Enforcement" is coordination of `Nom`
  datasets/oneoff/pdf/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.pdf
  datasets/oneoff/tex/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.tex
  datasets/oneoff/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.cgel
Labels: tree edit

#114 #105 usc-006: "(applicant so declared) qualified" :Comp -> :PredComp
  datasets/oneoff/pdf/usc-006.idbf22a95c-4f37-11ef-b6fb-9208f0a214ec_2_17.pdf
  datasets/oneoff/tex/usc-006.idbf22a95c-4f37-11ef-b6fb-9208f0a214ec_2_17.tex
  datasets/oneoff/usc-006.idbf22a95c-4f37-11ef-b6fb-9208f0a214ec_2_17.cgel
Labels: tree edit

#116 #104 usc-048: "notice" and "opportunity" is coordination of `Nom`
  datasets/oneoff/pdf/usc-048.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_1.pdf
  datasets/oneoff/tex/usc-048.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_1.tex
  datasets/oneoff/usc-048.id295cfc29-2a73-11ef-ba6d-a9961dfb011e_0_1.cgel
Labels: tree edit

#127 usc-027.id42e61ed9-f59a-11ee-8591-ff101ca1cce5_1_0.cgel
  datasets/oneoff/pdf/usc-027.id42e61ed9-f59a-11ee-8591-ff101ca1cce5_1_0.pdf
  datasets/oneoff/tex/usc-027.id42e61ed9-f59a-11ee-8591-ff101ca1cce5_1_0.tex
  datasets/oneoff/usc-027.id42e61ed9-f59a-11ee-8591-ff101ca1cce5_1_0.cgel
Labels: new tree

#155 more stubs
  datasets/oneoff/usc-074.id46f40846-50c2-11ef-a7e6-e6e97d13e696_1_0.cgel
  datasets/oneoff/usc-075.id46fb0cb3-50c2-11ef-a7e6-e6e97d13e696_1_0.cgel
  datasets/oneoff/usc-076.id470bd67b-50c2-11ef-a7e6-e6e97d13e696_2_0.cgel
  datasets/oneoff/usc-077.id47cf4d4d-50c2-11ef-a7e6-e6e97d13e696_2_0.cgel
  datasets/oneoff/usc-078.id48122293-50c2-11ef-a7e6-e6e97d13e696_1_0.cgel
  datasets/oneoff/usc-079.id48146cb0-50c2-11ef-a7e6-e6e97d13e696_2_0.cgel
  datasets/oneoff/usc-080.id481e08e1-50c2-11ef-a7e6-e6e97d13e696_1_0.cgel
  datasets/oneoff/usc-081.id48277ee1-50c2-11ef-a7e6-e6e97d13e696_2_0.cgel
  datasets/oneoff/usc-082.id878f15c3-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-083.id882c66aa-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-084.id882c66da-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-085.id884916cc-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-086.id88c2b38d-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-087.id88bdd235-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-088.id88bdd195-4e86-11ef-8795-d6c340cedfe7_2_0.cgel
  datasets/oneoff/usc-089.id88bb876f-4e86-11ef-8795-d6c340cedfe7.cgel
  datasets/oneoff/usc-090.id2562c3e9-2a73-11ef-91df-a37dd62a7297.cgel
  datasets/oneoff/usc-091.id2562c433-2a73-11ef-91df-a37dd62a7297_2_0.cgel
  datasets/oneoff/usc-092.id25677f71-2a73-11ef-91df-a37dd62a7297_2_0.cgel
  datasets/oneoff/usc-093.id25677f87-2a73-11ef-91df-a37dd62a7297_2_0.cgel
  datasets/oneoff/usc-094.ided9a5557-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-095.ided9f3811-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-096.ided9cc6ca-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-097.ideda3f326-f599-11ee-bdac-93aa70de1141_1_0.cgel
  datasets/oneoff/usc-098.idedd144d8-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-099.ideddaba03-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-100.idedeb834f-f599-11ee-bdac-93aa70de1141_2_0.cgel
  datasets/oneoff/usc-101.idee03519a-f599-11ee-bdac-93aa70de1141_2_0.cgel
Labels: new stubs

#156 #104 usc-001: rm NP layer in 'United States'
  datasets/oneoff/pdf/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.pdf
  datasets/oneoff/tex/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.tex
  datasets/oneoff/usc-001.idc64b92f8-fcac-11ee-ae40-eb498a365d7d_2_0.cgel
Labels: tree edit

#163 usc-074
  datasets/oneoff/pdf/usc-074.id46f40846-50c2-11ef-a7e6-e6e97d13e696_1_0.pdf
  datasets/oneoff/tex/usc-074.id46f40846-50c2-11ef-a7e6-e6e97d13e696_1_0.tex
  datasets/oneoff/usc-074.id46f40846-50c2-11ef-a7e6-e6e97d13e696_1_0.cgel
Labels: new tree

#130 usc-021.id5d3a0a9f-f599-11ee-babc-9b453f011230_2_0.cgel
  datasets/oneoff/pdf/usc-021.id5d3a0a9f-f599-11ee-babc-9b453f011230_2_0.pdf
  datasets/oneoff/tex/usc-021.id5d3a0a9f-f599-11ee-babc-9b453f011230_2_0.tex
  datasets/oneoff/usc-021.id5d3a0a9f-f599-11ee-babc-9b453f011230_2_0.cgel
Labels: new tree

#128 usc-046.idf3f05e5d-2a49-11ef-8437-855ef5b8fc19_2_0.cgel
  datasets/oneoff/pdf/usc-046.idf3f05e5d-2a49-11ef-8437-855ef5b8fc19_2_0.pdf
  datasets/oneoff/tex/usc-046.idf3f05e5d-2a49-11ef-8437-855ef5b8fc19_2_0.tex
  datasets/oneoff/usc-046.idf3f05e5d-2a49-11ef-8437-855ef5b8fc19_2_0.cgel
Labels: new tree

#124 usc-041.id41ideee181a0-2a49-11ef-8437-855ef5b8fc19_2_0.cgel
  datasets/oneoff/pdf/usc-041.id41ideee181a0-2a49-11ef-8437-855ef5b8fc19_2_0.pdf
  datasets/oneoff/tex/usc-041.id41ideee181a0-2a49-11ef-8437-855ef5b8fc19_2_0.tex
  datasets/oneoff/usc-041.id41ideee181a0-2a49-11ef-8437-855ef5b8fc19_2_0.cgel
Labels: new tree
